### ISSUE TITLE
Can't Save

### ISSUE THREAD

**Issue by InFeKtId** [rrirower/mrss-feed-manager#1]
When I create the File I click File > New > New Feed File and name it, Click the Checkmark and Fill out all my info then when I go to file all my options to save are gray and I can't save?

**Comment by rrirower** [comment]
Please insure that you provide a value for **all** fields with a **red** label.  The 'add' button (green button with white "+") will become enabled once all required values are provided.  Click it to add your video item to your library.  Then, click the Save button at the bottom right.

**Comment by InFeKtId** [comment]
I've done that and this is what I get it loads into the library just fine but the save will not un gray out
![image](https://user-images.githubusercontent.com/13801534/64573774-871e8900-d33a-11e9-886a-2e604130571c.png)

**Comment by InFeKtId** [comment]
See the Save is gray and unclickable

**Comment by rrirower** [comment]
Bug has been fixed.  Please install latest release.
